### ISSUE TITLE
Stops editor.css loading in 3.3.3

### ISSUE THREAD

**Issue by purplespider** [nathancox/silverstripe-customhtmleditorfield#19]
Just adding this module seems to stop the theme's editor.css file from being loaded in any HTMLEditorField, (SilverStripe 3.3.3).

Removing the CustomHTMLEditorLeftAndMainExtension seems to resolve it, but that's as far as I've been able to get.

**Comment by purplespider** [comment]
I have since reproduced this on a fresh SilverStripe 3.5.3 install too.

And narrowed it down to [CustomHTMLEditorField.js](https://github.com/nathancox/silverstripe-customhtmleditorfield/blob/master/javascript/CustomHTMLEditorField.js) which is required on [line 10 of CustomHTMLEditorLeftAndMainExtension](https://github.com/nathancox/silverstripe-customhtmleditorfield/blob/master/code/CustomHTMLEditorLeftAndMainExtension.php#L10).

**Comment by nathancox** [comment]
Yeah I'm just having a look at it now and it seems SS changed the way TinyMCE configs work.  I'm going to do some rejiggering, will update when I have it working again.

**Comment by nathancox** [comment]
I've just done a 1.1.0 release which seems to be working in SS3.3+ now.

**Comment by purplespider** [comment]
Works a treat! Thank you so much for fixing this so quickly Nathan, on a weekend as well!
